import { StyleSheet } from "react-native";

export const loginScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#020617",
  },
  keyboardView: {
    flex: 1,
  },
  safeArea: {
    backgroundColor: "transparent",
  },
  content: {
    flexGrow: 1,
    justifyContent: "flex-start",
    minHeight: "100%",
    paddingTop: 36,
    paddingBottom: 52,
    paddingHorizontal: 18,
    gap: 18,
  },
  headerBlock: {
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
    marginTop: 0,
    marginBottom: 14,
  },
  logo: {
    width: 112,
    height: 112,
    marginBottom: 6,
  },
  title: {
    fontSize: 30,
    fontWeight: "800",
    color: "#f8fafc",
  },
  subtitle: {
    fontSize: 15,
    color: "rgba(226, 232, 240, 0.96)",
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 280,
  },
  card: {
    backgroundColor: "rgba(15, 23, 42, 0.68)",
    borderRadius: 32,
    padding: 24,
    gap: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.32,
    shadowRadius: 32,
    elevation: 12,
  },
  forgotLink: {
    color: "#93c5fd",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
    marginTop: -2,
  },
  submitError: {
    color: "#fee2e2",
    backgroundColor: "rgba(127, 29, 29, 0.28)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 13,
    lineHeight: 18,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.42)",
  },
  rememberRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: -2,
  },
  rememberPressable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 4,
    paddingRight: 10,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.4,
    borderColor: "rgba(191, 219, 254, 0.42)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  checkboxChecked: {
    backgroundColor: "rgba(59, 130, 246, 0.22)",
    borderColor: "#93c5fd",
  },
  rememberLabel: {
    color: "rgba(226, 232, 240, 0.86)",
    fontSize: 13,
    fontWeight: "700",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  footerText: {
    color: "rgba(226, 232, 240, 0.78)",
    fontSize: 14,
  },
  footerLink: {
    color: "#bfdbfe",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryAction: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    marginTop: 0,
  },
  secondaryLink: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 0.12,
  },
});
