import { StyleSheet } from "react-native";

export const signupScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#020617",
  },
  keyboardView: {
    flex: 1,
  },
  safeArea: {
    backgroundColor: "transparent",
  },
  content: {
    flexGrow: 1,
    minHeight: "100%",
    paddingTop: 24,
    paddingBottom: 60,
    paddingHorizontal: 18,
    gap: 18,
  },
  headerBlock: {
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 18,
    paddingTop: 0,
    marginBottom: 12,
  },
  logo: {
    width: 112,
    height: 112,
  },
  title: {
    fontSize: 29,
    fontWeight: "800",
    color: "#f8fafc",
  },
  subtitle: {
    fontSize: 15,
    color: "rgba(226, 232, 240, 0.96)",
    textAlign: "center",
    lineHeight: 22,
    maxWidth: 290,
  },
  card: {
    backgroundColor: "rgba(15, 23, 42, 0.68)",
    borderRadius: 32,
    padding: 24,
    gap: 14,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.32,
    shadowRadius: 32,
    elevation: 12,
  },
  selectorBlock: {
    gap: 8,
  },
  customFieldLabel: {
    color: "rgba(241, 245, 249, 0.92)",
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.15,
  },
  customFieldShell: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1.25,
    borderColor: "rgba(255, 255, 255, 0.14)",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    paddingHorizontal: 16,
    justifyContent: "center",
  },
  readOnlyFieldShell: {
    opacity: 0.92,
  },
  customFieldShellError: {
    borderColor: "rgba(248, 113, 113, 0.9)",
    backgroundColor: "rgba(127, 29, 29, 0.2)",
  },
  customFieldValue: {
    color: "#f8fafc",
    fontSize: 15,
  },
  customFieldPlaceholder: {
    color: "rgba(226, 232, 240, 0.62)",
  },
  fieldError: {
    color: "#fecaca",
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
    backgroundColor: "rgba(127, 29, 29, 0.28)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.32)",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  datePickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.72)",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  datePickerBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  datePickerCard: {
    backgroundColor: "rgba(15, 23, 42, 0.98)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    padding: 20,
    gap: 16,
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.34,
    shadowRadius: 28,
    elevation: 16,
  },
  datePickerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  datePickerTitle: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  datePickerClose: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(59, 130, 246, 0.16)",
  },
  datePickerCloseText: {
    color: "#bfdbfe",
    fontSize: 13,
    fontWeight: "700",
  },
  datePickerMonthRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  datePickerArrow: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  datePickerMonthControls: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
  },
  datePickerHeaderPill: {
    minHeight: 40,
    paddingHorizontal: 14,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
  },
  datePickerHeaderPillActive: {
    backgroundColor: "rgba(37, 99, 235, 0.2)",
    borderColor: "rgba(96, 165, 250, 0.55)",
  },
  datePickerHeaderPillText: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "700",
  },
  datePickerHeaderPillTextActive: {
    color: "#dbeafe",
  },
  datePickerArrowText: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 24,
  },
  datePickerWeekdays: {
    flexDirection: "row",
  },
  datePickerCellSlot: {
    width: "14.2857%",
    padding: 3,
  },
  datePickerWeekdayText: {
    textAlign: "center",
    color: "rgba(226, 232, 240, 0.7)",
    fontSize: 12,
    fontWeight: "700",
  },
  datePickerGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  datePickerDay: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  datePickerDayActive: {
    backgroundColor: "#2563eb",
    borderColor: "#1d4ed8",
  },
  datePickerDayDisabled: {
    opacity: 0.34,
  },
  datePickerDayText: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "700",
  },
  datePickerDayTextActive: {
    color: "#ffffff",
  },
  datePickerDayTextDisabled: {
    color: "rgba(226, 232, 240, 0.48)",
  },
  selectionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
    rowGap: 8,
  },
  selectionGridItem: {
    width: "33.3333%",
    paddingHorizontal: 4,
  },
  selectionPill: {
    minHeight: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.12)",
    paddingHorizontal: 12,
  },
  selectionPillActive: {
    backgroundColor: "rgba(37, 99, 235, 0.24)",
    borderColor: "rgba(96, 165, 250, 0.65)",
  },
  selectionPillText: {
    color: "#f8fafc",
    fontSize: 14,
    fontWeight: "700",
  },
  selectionPillTextActive: {
    color: "#dbeafe",
  },
  yearScroll: {
    maxHeight: 260,
  },
  submitError: {
    color: "#fee2e2",
    backgroundColor: "rgba(127, 29, 29, 0.24)",
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    lineHeight: 19,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.32)",
    fontWeight: "600",
  },
  agreementSection: {
    gap: 8,
  },
  agreementRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  checkboxTapTarget: {
    marginTop: -2,
    padding: 2,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.24)",
    backgroundColor: "rgba(255, 255, 255, 0.06)",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  checkboxChecked: {
    backgroundColor: "#2563eb",
    borderColor: "#2563eb",
  },
  checkboxError: {
    borderColor: "rgba(248, 113, 113, 0.9)",
    backgroundColor: "rgba(127, 29, 29, 0.2)",
  },
  agreementText: {
    flex: 1,
    color: "rgba(241, 245, 249, 0.92)",
    fontSize: 13,
    lineHeight: 21,
  },
  linkText: {
    color: "#93c5fd",
    textDecorationLine: "underline",
    fontWeight: "800",
  },
  footerRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  footerText: {
    color: "rgba(226, 232, 240, 0.78)",
    fontSize: 14,
  },
  footerLink: {
    color: "#bfdbfe",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryAction: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 4,
    marginTop: 0,
  },
  secondaryLink: {
    color: "rgba(226, 232, 240, 0.76)",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: 0.12,
  },
  policyOverlay: {
    flex: 1,
    backgroundColor: "rgba(2, 6, 23, 0.72)",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  policyBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  policyCard: {
    maxHeight: "76%",
    backgroundColor: "rgba(15, 23, 42, 0.98)",
    borderRadius: 28,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    padding: 20,
    gap: 16,
    shadowColor: "#020617",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.34,
    shadowRadius: 28,
    elevation: 16,
  },
  policyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  policyTitle: {
    flex: 1,
    color: "#f8fafc",
    fontSize: 18,
    fontWeight: "800",
  },
  policyClose: {
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(59, 130, 246, 0.16)",
  },
  policyCloseText: {
    color: "#bfdbfe",
    fontSize: 13,
    fontWeight: "700",
  },
  policyScroll: {
    flexGrow: 0,
  },
  policyScrollContent: {
    gap: 14,
    paddingBottom: 4,
  },
  policySection: {
    gap: 6,
  },
  policySectionTitle: {
    color: "#f8fafc",
    fontSize: 15,
    fontWeight: "800",
  },
  policyBody: {
    color: "rgba(226, 232, 240, 0.92)",
    fontSize: 14,
    lineHeight: 22,
  },
});
