import { StyleSheet } from "react-native";

export function createResidentReportDetailsStyles(theme) {
  return StyleSheet.create({
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    emptyText: {
      color: theme.textMuted,
      fontSize: 16,
    },
    summaryCard: {
      backgroundColor: theme.surface,
      borderRadius: 24,
      padding: 18,
      gap: 14,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadowStrong,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 18,
      elevation: 4,
    },
    summaryHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
    },
    summaryCopy: {
      flex: 1,
      gap: 4,
    },
    summaryTitle: {
      color: theme.text,
      fontSize: 20,
      fontWeight: "900",
      lineHeight: 26,
    },
    summaryMeta: {
      color: theme.textMuted,
      fontSize: 13,
      fontWeight: "700",
    },
    confirmationBanner: {
      minHeight: 44,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: theme.primarySoft,
      borderWidth: 1,
      borderColor: "rgba(79, 131, 255, 0.22)",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    confirmationBannerText: {
      flex: 1,
      color: theme.primary,
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 19,
    },
    photoWrap: {
      overflow: "hidden",
      borderRadius: 24,
    },
    card: {
      backgroundColor: theme.surface,
      borderRadius: 24,
      padding: 18,
      gap: 12,
      borderWidth: 1,
      borderColor: theme.border,
    },
    sectionTitle: {
      color: theme.text,
      fontSize: 16,
      fontWeight: "900",
    },
    label: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: "700",
    },
    value: {
      color: theme.textMuted,
      fontSize: 15,
      lineHeight: 22,
      fontWeight: "600",
    },
    seeMoreText: {
      color: theme.primary,
      fontSize: 13,
      fontWeight: "800",
    },
    infoRow: {
      gap: 12,
    },
    infoBlock: {
      gap: 6,
    },
    reasonBanner: {
      minHeight: 44,
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: theme.dangerSoft,
      borderWidth: 1,
      borderColor: "rgba(248, 113, 113, 0.22)",
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    reasonBannerText: {
      flex: 1,
      color: theme.danger,
      fontSize: 13,
      fontWeight: "700",
      lineHeight: 19,
    },
    primaryButton: {
      backgroundColor: theme.primary,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: "center",
    },
    primaryButtonText: {
      color: "#ffffff",
      fontWeight: "800",
      fontSize: 15,
    },
    secondaryButton: {
      backgroundColor: theme.primarySoft,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: "center",
      borderWidth: 1,
      borderColor: "rgba(79, 131, 255, 0.22)",
    },
    secondaryButtonText: {
      color: theme.primary,
      fontWeight: "800",
      fontSize: 15,
    },
    confirmationRow: {
      gap: 10,
    },
    confirmButton: {
      backgroundColor: theme.success,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: "center",
    },
    disputeButton: {
      backgroundColor: theme.danger,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: "center",
    },
    actionButtonText: {
      color: "#ffffff",
      fontWeight: "800",
      fontSize: 15,
    },
  });
}
